### PR TITLE
OSIDB-2693 : Fix Deleted Affects after flaw save

### PR DESCRIPTION
**Pull request by tboyetteredhat**
# [[OSIDB-2693](https://issues.redhat.com/browse/OSIDB-2693)] [Affected Offerings To Be Deleted message stays after deletion]

## Checklist:

- [x] Linting passed
- [x] Type checks passed
- [x] Tests suite passed
- [x] Commits consolidated
- [x] Changelog updated
- [x] Test cases added/updated
- [x] Jira ticket updated

## Summary:

Affected Offerings To Be Deleted message stays after deletion

## Changes:

[Replace with a detailed description of the changes made in this PR, including any new features, enhancements, bug fixes, or refactorings.]

## Considerations:

[Replace with any additional considerations, notes, or instructions for reviewers.]

### CODE REVIEW

**Review by superbuggy — COMMENTED** [review]
I think it would be simpler to create a function to reset modified and deleted affects after a save. WDYT?

**Comment by tboyetteredhat** [comment]
> I think it would be simpler to create a function to reset modified and deleted affects after a save. WDYT?

Agree, Thanks for your comment.

**Comment by superbuggy** [comment]
> > I think it would be simpler to create a function to reset modified and deleted affects after a save. WDYT?
> 
> Agree, Thanks for your comment.

I think adding the reset function to `useFlawAffectsModel` and returning it from that function would make it relatively easy to perform cleanup here and here

https://github.com/RedHatProductSecurity/osim/blob/fix/OSIDB-2765-error-recovery-on-flaw-create/src/composables/useFlawModel.ts#L144

https://github.com/RedHatProductSecurity/osim/blob/fix/OSIDB-2765-error-recovery-on-flaw-create/src/composables/useFlawModel.ts#L136

**Comment by tboyetteredhat** [comment]
> > > I think it would be simpler to create a function to reset modified and deleted affects after a save. WDYT?
> > 
> > 
> > Agree, Thanks for your comment.
> 
> I think adding the reset function to `useFlawAffectsModel` and returning it from that function would make it relatively easy to perform cleanup here and here
> 
> https://github.com/RedHatProductSecurity/osim/blob/fix/OSIDB-2765-error-recovery-on-flaw-create/src/composables/useFlawModel.ts#L144
> 
> https://github.com/RedHatProductSecurity/osim/blob/fix/OSIDB-2765-error-recovery-on-flaw-create/src/composables/useFlawModel.ts#L136

You mean, we don't need to show deleted affects after flaw save? Also I think we need to call reset after flaw save successfully . I think this place only. https://github.com/RedHatProductSecurity/osim/blob/fix/OSIDB-2765-error-recovery-on-flaw-create/src/composables/useFlawModel.ts#L144

**Review by C-Valen — APPROVED** [review]

**Comment by superbuggy** [comment]
> You mean, we don't need to show deleted affects after flaw save? Also I think we need to call reset after flaw save successfully . I think this place only. https://github.com/RedHatProductSecurity/osim/blob/fix/OSIDB-2765-error-recovery-on-flaw-create/src/composables/useFlawModel.ts#L144

I think that's reasonable. My thought was if there was an error during save, just to clean up the clutter on screen to make it easier to track down a problem with the form input data if there was a problem with the data.

**Review by d10n — APPROVED** [review]
Looks great

**Pull request merged**
