### PR TITLE
Changelog: Release v2024-6-0 update

### PR DESCRIPTION
**Pull request by C-Valen**
# Changelog: Release v2024-6-0 update

## Checklist:

- [x] Linting passed
- [x] Type checks passed
- [x] Tests suite passed
- [x] Commits consolidated
- [x] Changelog updated
- [x] Test cases added/updated
- [x] Jira ticket updated

## Summary:

Updates the changelog for the last release [OSIM v2024.6.0](https://github.com/RedHatProductSecurity/osim/releases/tag/v2024.6.0)

## Changes:

- Change unrelased to release version

## Considerations:

- Should we include this on the released tag?
- There is a bunch of items on "[Unreleased] (TODO update for 2024.1.1 and 2024.2.0 releases)" but I didn't find any of these tags. Not sure what to do with that, should be included in this release?

### CODE REVIEW

**Review by MrMarble — APPROVED** [review]

**Review by JakubFrejlach — COMMENTED** [review]
I am honest now a little bit lost regarding the changelog compared to what do we have on state/uat/prod, how do we differentiate that?

**Comment by MrMarble** [comment]
I noticed the previous release is also in `unreleased`
https://github.com/RedHatProductSecurity/osim/blob/b722f6f48ca0e042f57173c2ecef27926c7d1b7d/CHANGELOG.md?plain=1#L69

**Comment by C-Valen** [comment]
> I am honestly now a little bit lost regarding the changelog compared to what do we have on state/uat/prod, how do we differentiate that?

This PR currently have only the changes for release tag v2024.6.0 so we can just move everything newer to a fresh new unreased block.

> I noticed the previous release is also in `unreleased`
> 
> https://github.com/RedHatProductSecurity/osim/blob/b722f6f48ca0e042f57173c2ecef27926c7d1b7d/CHANGELOG.md?plain=1#L69

Yes, I noticed the same, we should clarify what to do with all those, I think the tags they refer to does not exist.

**Review by tboyetteredhat — APPROVED** [review]

**Review by d10n — APPROVED** [review]
I have updates in progress to revise older history which will be ready soon

**Pull request merged**
