### PR TITLE
Simple container build and push test

### PR DESCRIPTION
**Pull request by sfxworks**
Will require tweaking. Currently having trouble building with latest commits.

### CODE REVIEW

**Comment by sfxworks** [comment]
@d10n Please review container build errors at 
https://github.com/RedHatProductSecurity/ir-web-ui/actions/runs/4750582415/jobs/8438895896

```
Step 5/7 : RUN yarn build  # Use "yarn build" to create a production build
 ---> Running in 689bdcf77177
yarn run v1.22.19
$ run-p type-check build-only
$ vue-tsc --noEmit
$ vite build
vite v4.1.4 building for production...
transforming...
[plugin:vite:esbuild] This assignment will throw because "requestReview" is a constant
100|                  type: "checkbox",
101|                  id: "request-review",
102|                  "onUpdate:modelValue": _cache[0] || (_cache[0] = ($event: any) => ((requestReview) = $event))
   |                                                                                      ^
103|                }, null, 512), [
104|                  [_vModelCheckbox, requestReview]
```

**Comment by sfxworks** [comment]
@d10n ready to review

**Comment by sfxworks** [comment]
Ready for review

Few things to note:
1. Internal discussions and limitations have pushed us to use quay. A generic repo has been made now. An org referenced one can be used in the future and swapped using the variable in the repo. Ref: https://source.redhat.com/departments/it/devit/it-infrastructure/itcloudservices/itocp/managedplatformplushub/mppluswiki/managed_platform_plus_approved_image_registries

2. Rough documentation has been made against the bottom of the README describing the GH action process

3. Openshift spec has been placed in the openshfit folder.

**Review by d10n — APPROVED** [review]
Great work!

**Pull request merged**
